fix(checks): Use the more accurate term "revision" instead of "remote"

diff --git a/lefthook.yaml b/lefthook.yaml
--- a/lefthook.yaml
+++ b/lefthook.yaml
@@ -282,12 +282,12 @@ check:
             range="$(git merge-base '@{push}' HEAD).."
             ;;
           'not-in-'*)
-            remote="${LEFTHOOK_FILES#not-in-}"
-            if ! git rev-parse --verify --quiet "$remote" >/dev/null; then
-              echo "error: Remote '$remote' does not exist" >&2
+            revision="${LEFTHOOK_FILES#not-in-}"
+            if ! git rev-parse --verify --quiet "$revision" >/dev/null; then
+              echo "error: Revision '$revision' does not exist" >&2
               exit 1
             fi
-            range="$(git merge-base "$remote" 'HEAD').."
+            range="$(git merge-base "$revision" 'HEAD').."
             ;;
           'head')
             range='HEAD^!'
