cleanup

diff --git a/dotfiles/git/bin/git-r b/dotfiles/git/bin/git-r
--- a/dotfiles/git/bin/git-r
+++ b/dotfiles/git/bin/git-r
@@ -1,13 +1,10 @@
 #!/usr/bin/env sh
 
-# Exit if a command returns a non-zero exit code
 set -o errexit
-
-# Exit if an unset variable is referenced
 set -o nounset
 
 if [ $# -eq 0 ]; then
-    echo "ERROR: You must provide the number of commits to rebase"
+    echo "ERROR: You must provide the number of commits to rebase" >&2
     exit 1
 fi
 
