ci: Account for failed/cancelled dependencies of required checks

diff --git a/.github/workflows/check-pull-request.yml b/.github/workflows/check-pull-request.yml
--- a/.github/workflows/check-pull-request.yml
+++ b/.github/workflows/check-pull-request.yml
@@ -129,7 +129,13 @@ jobs:
   # don't change it without updating the required checks as well.
   ensure-generated-code-is-up-to-date:
     needs: codegen-changed-files
-    if: needs.codegen-changed-files.outputs.any-changed == 'true'
+    # By default, if the dependency of a required check fails or is cancelled, the
+    # required check is skipped and counted as a successful check[1]. So in addition
+    # to checking if a relevant file was changed, I also need to check to see if a
+    # dependency failed or was cancelled. If it was, I'll fail this job as well.
+    #
+    # [1]: https://github.com/actions/runner/issues/2566
+    if: ${{ (contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')) || needs.codegen-changed-files.outputs.any-changed == 'true' }}
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -140,6 +146,12 @@ jobs:
         with:
           dev-shell: ciCodegen
           cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
+      - if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
+        env:
+          REASON: ${{ contains(needs.*.result, 'cancelled') && 'was cancelled' || '' }}${{ contains(needs.*.result, 'failure') && 'failed' || '' }}
+        run: |
+          echo "Error: Dependency job $REASON"
+          exit 1
       - env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
